# GitHub Actions allows you to build, test, and deploy applications in your language of choice
name: Node CI

on:
  push:
    branches: [main, develop, v1-dev]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on node ${{ matrix.node }} and ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    runs-on: ${{ matrix.os }}

    steps:
    # checkout the repo
    - name: Checkout the repo
      uses: actions/checkout@v3

    # use node.js matrix
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    # install dependencies and build
    - name: Install deps and build
      run: yarn install
